"use client";
import { useCallback, useEffect, useState } from "react";
import { CalendarPlus, CalendarRange, ExternalLink, RefreshCw, ShieldCheck } from "lucide-react";
import styles from "./seasons.module.css";

type Season = { key:string; label:string; status:string; nakkaLeagueId:string; sourceUrl:string; eloPolicy:string; active:boolean; leagueTitle?:string; eventCount?:number; lastScanAt?:string; lastError?:string; teamAliases?:Record<string,{canonical:string;display:string}> };
type PreviewEvent = { id:string; title:string; startDate?:string; sourceUrl:string; status:"READY"|"ALREADY_IMPORTED"|"DATE_REQUIRED"; aliasLinks:string[] };
type Preview = { season:{key:string;label:string}; events:PreviewEvent[]; summary:{total:number;ready:number;duplicates:number;dateRequired:number} };

export default function SeasonsPage(){
 const [seasons,setSeasons]=useState<Season[]>([]); const [busy,setBusy]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [preview,setPreview]=useState<Preview|null>(null);
 const load=useCallback(async()=>{const r=await fetch("/api/admin/backend/api/v1/seasons/admin",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.detail||p.error);setSeasons(p.seasons||[])},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function post(path:string,body:unknown){const r=await fetch(`/api/admin/backend/api/v1/seasons/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.detail||p.error||"Action impossible");return p}
 async function scan(key:string){setBusy(`scan-${key}`);setError("");setMessage("");try{const p=await post("scan",{key});setMessage(`Saison ${key} vérifiée : ${p.season.eventCount??0} rencontre(s) détectée(s).`);await load();if(key==="2026-2027")await showPreview(key)}catch(e){setError(e instanceof Error?e.message:"Analyse impossible")}finally{setBusy("")}}
 async function showPreview(key:string){setBusy(`preview-${key}`);setError("");try{setPreview(await post("calendar/preview",{key}))}catch(e){setError(e instanceof Error?e.message:"Aperçu impossible")}finally{setBusy("")}}
 async function importAll(){if(!preview||!window.confirm(`Importer ${preview.summary.ready} rencontre(s) dans le calendrier ?`))return;setBusy("import");setError("");try{const p=await post("calendar/import",{key:preview.season.key,confirmed:true});setMessage(`${p.createdCount} rencontre(s) ajoutée(s), ${p.skippedCount} doublon(s) ignoré(s), ${p.incompleteCount} date(s) à confirmer.`);await showPreview(preview.season.key)}catch(e){setError(e instanceof Error?e.message:"Import impossible")}finally{setBusy("")}}
 return <main className={styles.page}><section className={styles.hero}><div><span>SPRINT 20 · MULTI-SAISON</span><h1>Saisons du championnat</h1><p>Deux sources Nakka indépendantes, sans écraser l’historique 2026.</p></div><CalendarRange/></section>{message&&<p className={styles.success}>{message}</p>}{error&&<p className={styles.error}>{error}</p>}<section className={styles.grid}>{seasons.map(s=><article key={s.key} className={s.active?styles.active:""}><header><div><span>{s.status}</span><h2>{s.label}</h2></div>{s.active&&<em>Surveillance active</em>}</header><dl><div><dt>Identifiant Nakka</dt><dd>{s.nakkaLeagueId}</dd></div><div><dt>Titre détecté</dt><dd>{s.leagueTitle||"À confirmer"}</dd></div><div><dt>Rencontres</dt><dd>{s.eventCount??"—"}</dd></div><div><dt>Dernière analyse</dt><dd>{s.lastScanAt?new Date(s.lastScanAt).toLocaleString("fr-FR"):"Jamais"}</dd></div><div><dt>Politique ELO</dt><dd><ShieldCheck/> Continuité de carrière</dd></div>{s.teamAliases&&<div><dt>Alias équipes</dt><dd>{Object.entries(s.teamAliases).map(([name,value])=><span className={styles.alias} key={name}>{name} ↔ {value.canonical}</span>)}</dd></div>}</dl>{s.lastError&&<p className={styles.warning}>{s.lastError}</p>}<footer><button disabled={!!busy} onClick={()=>void scan(s.key)}><RefreshCw/> {busy===`scan-${s.key}`?"Analyse…":"Analyser"}</button>{s.key==="2026-2027"&&<button className={styles.secondary} disabled={!!busy||!s.eventCount} onClick={()=>void showPreview(s.key)}><CalendarPlus/> Préparer le calendrier</button>}<a href={s.sourceUrl} target="_blank" rel="noreferrer">Ouvrir Nakka <ExternalLink/></a></footer></article>)}</section>{preview&&<section className={styles.preview}><header><div><span>APERÇU AVANT PUBLICATION</span><h2>{preview.season.label} · {preview.summary.total} rencontres</h2></div><button disabled={!!busy||preview.summary.ready===0} onClick={()=>void importAll()}><CalendarPlus/> Importer les {preview.summary.ready} rencontres prêtes</button></header><div className={styles.summary}><span>{preview.summary.ready} prêtes</span><span>{preview.summary.duplicates} déjà présentes</span><span>{preview.summary.dateRequired} dates à confirmer</span></div><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Rencontre Nakka</th><th>Rattachement historique</th><th>État</th></tr></thead><tbody>{preview.events.map(e=><tr key={e.id}><td>{e.startDate||"À confirmer"}</td><td><strong>{e.title}</strong><small>{e.id}</small></td><td>{e.aliasLinks.length?e.aliasLinks.map(x=><small key={x}>{x}</small>):"—"}</td><td><span className={`${styles.state} ${styles[e.status.toLowerCase()]}`}>{e.status==="READY"?"Prête":e.status==="ALREADY_IMPORTED"?"Déjà importée":"Date requise"}</span></td></tr>)}</tbody></table></div></section>}<p className={styles.note}>PDC A reste rattachée à PDC Neige et PDC B à PDC Fournaise pour l’historique. Le calendrier affiche les noms officiels 2026–2027.</p></main>
}
