import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';

const source = readFileSync(new URL('../lib/bdc.ts', import.meta.url), 'utf8');
const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } });
const { bdcPoints, bdcStandings, bdcCalendarRound } = await import(`data:text/javascript;base64,${Buffer.from(outputText).toString('base64')}`);
assert.equal(bdcPoints(1, 5, 8), 11, 'Pool bonus capped at three');
assert.equal(bdcPoints(8, 0, 8), 2);
assert.equal(bdcPoints(12, 1, 12), 2);
assert.throws(() => bdcPoints(9, 0, 8));
assert.throws(() => bdcPoints(1, -1, 8));
assert.throws(() => bdcPoints(1.5, 0, 8));
const a = { id: 'a', name: 'A' }, b = { id: 'b', name: 'B' }, c = { id: 'c', name: 'C' };
const round = (number, players, place = 1, poolWins = 2) => ({ round: number, teamCount: 8, teams: [{ id: `duo-${number}`, players, place, poolWins }] });
const rows = bdcStandings([round(1, [a, b]), round(2, [a, c]), round(3, [a, b])]);
assert.equal(rows.find(row => row.id === 'a').total, 30, 'Keep points when changing partner');
assert.equal(rows.find(row => row.id === 'b').total, 20, 'Full points for each partner');
assert.equal(rows.find(row => row.id === 'a').eligible, true);
assert.equal(rows.find(row => row.id === 'b').eligible, false);
assert.equal(rows.find(row => row.id === 'a').participations, 3);
assert.equal(rows.find(row => row.id === 'b').points[1], null, 'No attendance is not a zero result');
const tied = bdcStandings([round(1, [a, b])]);
assert.deepEqual(tied.map(row => row.rank), [1, 1], 'Do not invent tie-breaks');
const pending = bdcStandings([round(1, [a, b], null, null)]);
assert.equal(pending[0].pending, true);
assert.equal(pending[0].points[0], null);
assert.throws(() => bdcStandings([round(1, [a, a])]), /Joueur/);
assert.throws(() => bdcStandings([round(1, [a, b]), round(1, [a, c])]), /Manche/);
assert.throws(() => bdcStandings([round(7, [a, b])]), /Manche/);
assert.equal(bdcCalendarRound('Blind Draw Championship by TDC - Manche 1', '2026-09-11').number, 1);
assert.equal(bdcCalendarRound('Autre tournoi', '2026-09-11'), undefined);
assert.deepEqual(bdcStandings([]), []);
console.log('BDC checks passed: individual points, partner changes, participation, bonus, ties and invalid inputs.');
