"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, CalendarClock, Search, XCircle } from "lucide-react";
import styles from "./transfers.module.css";

type Player={id:string;name:string;team?:string;club?:string}; type Transfer={id:string;player_id:string;player_name:string;from_team?:string;from_club?:string;target_team?:string;target_club?:string;effective_date:string;note?:string;computed_status:string};
const empty={player_id:"",target_club:"",target_team:"",effective_date:"",note:""};
export default function TransfersPage(){
 const [players,setPlayers]=useState<Player[]>([]),[transfers,setTransfers]=useState<Transfer[]>([]);const [form,setForm]=useState(empty),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const selected=players.find(p=>p.id===form.player_id);const filtered=useMemo(()=>players.filter(p=>`${p.name} ${p.team||""} ${p.club||""}`.toLowerCase().includes(query.toLowerCase())).slice(0,30),[players,query]);
 const load=useCallback(async()=>{const r=await fetch("/api/admin/backend/api/v1/player-transfers/admin",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.detail||p.error);setPlayers(p.players||[]);setTransfers(p.transfers||[])},[]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function post(path:string,body:unknown){const r=await fetch(`/api/admin/backend/api/v1/player-transfers/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.detail||p.error);return p}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{await post("upsert",form);setMessage(`Transfert de ${selected?.name} programmé au ${new Date(`${form.effective_date}T12:00:00`).toLocaleDateString("fr-FR")}.`);setForm(empty);setQuery("");await load()}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible")}finally{setBusy(false)}}
 async function cancel(row:Transfer){if(!confirm(`Annuler le transfert de ${row.player_name} ?`))return;setBusy(true);try{await post("cancel",{id:row.id,confirmed:true});setMessage("Transfert annulé.");await load()}catch(e){setError(e instanceof Error?e.message:"Annulation impossible")}finally{setBusy(false)}}
 return <main className={styles.page}><section className={styles.hero}><div><span>GESTION DES EFFECTIFS</span><h1>Joueurs & transferts</h1><p>Programme un changement d’équipe, de club ou les deux, avec une date d’effet.</p></div><ArrowRightLeft/></section>{message&&<p className={styles.success}>{message}</p>}{error&&<p className={styles.error}>{error}</p>}<div className={styles.columns}><form onSubmit={save} className={styles.form}><header><CalendarClock/><div><span>NOUVEAU MOUVEMENT</span><h2>Programmer un transfert</h2></div></header><label>Rechercher un joueur<div className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, équipe ou club"/></div></label><label>Joueur<select required value={form.player_id} onChange={e=>setForm({...form,player_id:e.target.value})}><option value="">Choisir…</option>{filtered.map(p=><option key={p.id} value={p.id}>{p.name} · {p.team||"sans équipe"}</option>)}</select></label>{selected&&<div className={styles.current}><span>Affectation actuelle</span><strong>{selected.team||"Équipe inconnue"}</strong><small>{selected.club||"Club inconnu"}</small></div>}<label>Nouveau club<input value={form.target_club} onChange={e=>setForm({...form,target_club:e.target.value})} placeholder={selected?.club||"Ex. Papangue Darts Club"}/></label><label>Nouvelle équipe<input value={form.target_team} onChange={e=>setForm({...form,target_team:e.target.value})} placeholder="Ex. PDC A"/></label><label>Date d’effet<input required type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label><label>Note facultative<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Mutation annoncée, changement de composition…"/></label><button disabled={busy||!form.player_id}>{busy?"Enregistrement…":"Programmer le transfert"}</button></form><section className={styles.list}><header><div><span>HISTORIQUE ET PRÉVISIONS</span><h2>{transfers.length} mouvement(s)</h2></div></header>{transfers.length?transfers.map(t=><article key={t.id}><div><span className={styles[t.computed_status.toLowerCase()]}>{t.computed_status==="SCHEDULED"?"Programmé":t.computed_status==="APPLIED"?"Effectif":"Annulé"}</span><h3>{t.player_name}</h3><p>{t.from_team||"—"} → <strong>{t.target_team||"—"}</strong></p><small>{t.from_club||"—"} → {t.target_club||"—"} · {new Date(`${t.effective_date}T12:00:00`).toLocaleDateString("fr-FR")}</small></div>{t.computed_status==="SCHEDULED"&&<button title="Annuler" disabled={busy} onClick={()=>void cancel(t)}><XCircle/></button>}</article>):<div className={styles.empty}>Aucun transfert programmé.</div>}</section></div></main>
}
