import {chromium,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const output=resolve(root,'docs/ranking-workflow-preview');
const sharp=createRequire(resolve(root,'app/frontend/package.json'))('sharp');
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const adminContext=await browser.newContext({bypassCSP:true,viewport:{width:1440,height:1100}});
const dsContext=await browser.newContext({bypassCSP:true,viewport:{width:1440,height:1100}});
const admin=await adminContext.newPage(),ds=await dsContext.newPage();
async function screenshot(page,name){await page.addStyleTag({content:'nextjs-portal{display:none!important}'});await sharp(await page.screenshot({fullPage:true})).webp({lossless:true}).toFile(output+'/'+name.replace(/\.png$/,'.webp'));}
async function login(page,role){
 await page.goto('http://127.0.0.1:3008/login');
 await page.locator('input[type=email]').fill(role+'@example.invalid');
 await page.locator('input[type=password]').fill('preview-only');
 await page.locator('form button').first().click();
 await page.waitForURL(role==='admin'?'**/admin':'**/directeur-sportif',{timeout:30000});
}
try{
 await login(admin,'admin');
 await admin.goto('http://127.0.0.1:3008/admin/classement-individuel');
 await expect(admin.getByText('Open Club Double · Démonstration',{exact:true})).toBeVisible({timeout:30000});
 await screenshot(admin,'01-administration.png');
 await admin.getByRole('button',{name:'Ouvrir →'}).click();
 await expect(admin.getByRole('heading',{name:'Open Club Double · Démonstration'})).toBeVisible();
 await expect(admin.getByRole('button',{name:'Envoyer au Directeur sportif'})).toBeDisabled();
 await admin.getByLabel('Je confirme avoir contrôlé cette version et son impact sur le classement.').check();
 await admin.getByRole('button',{name:'Envoyer au Directeur sportif'}).click();
 await expect(admin.getByText('À valider par le DS · v2',{exact:true})).toBeVisible();
 await login(ds,'director');
 await ds.getByRole('button',{name:'Ouvrir →'}).click();
 await expect(ds.getByRole('button',{name:'Demander une correction'})).toBeDisabled();
 await screenshot(ds,'02-directeur-sportif.png');
 await ds.getByLabel('Commentaire (obligatoire pour une correction)').fill('Merci de préciser la référence de la finale.');
 await ds.getByRole('button',{name:'Demander une correction'}).click();
 await expect(ds.getByText('Correction demandée · v2',{exact:true})).toBeVisible();
 await admin.getByRole('button',{name:'Actualiser',exact:true}).click();
 await admin.getByRole('button',{name:'Corriger / compléter'}).click();
 await admin.getByLabel('Référence du classement sportif officiel').fill('Feuille de finale fictive vérifiée : Alice / Bruno gagnent 3–1.');
 await admin.getByLabel('Motif de la modification').fill('Référence de la finale précisée à la demande du DS.');
 await admin.getByRole('button',{name:'Enregistrer une nouvelle version'}).click();
 await expect(admin.getByText('À contrôler · v3',{exact:true})).toBeVisible();
 await admin.getByLabel('Je confirme avoir contrôlé cette version et son impact sur le classement.').check();
 await admin.getByRole('button',{name:'Envoyer au Directeur sportif'}).click();
 await expect(admin.getByText('À valider par le DS · v3',{exact:true})).toBeVisible();
 await ds.getByRole('button',{name:'Actualiser',exact:true}).click();
 await ds.getByLabel('Je confirme avoir contrôlé les résultats et le classement de cette compétition.').check();
 await ds.getByRole('button',{name:'Valider les résultats · v3'}).click();
 await expect(ds.getByText('Validé par le DS · v3',{exact:true})).toBeVisible();
 await admin.getByRole('button',{name:'Actualiser',exact:true}).click();
 await admin.getByLabel('Je confirme avoir contrôlé cette version et son impact sur le classement.').check();
 await admin.getByRole('button',{name:'Valider le contrôle final'}).click();
 await expect(admin.getByText('Prêt à publier · v3',{exact:true})).toBeVisible();
 await screenshot(admin,'03-controle-final.png');
 await admin.getByLabel('Je confirme avoir contrôlé cette version et son impact sur le classement.').check();
 await admin.getByRole('button',{name:'Publier et mettre à jour le classement'}).click();
 await expect(admin.getByText('Publié · v3',{exact:true})).toBeVisible();
 const publicData=await (await admin.request.get('http://127.0.0.1:8008/api/v1/committee-ranking')).json();
 expect(publicData.rankings.mixed.map(r=>r.total).sort((a,b)=>b-a)).toEqual([10,10,8,8]);
 await admin.goto('http://127.0.0.1:3008/competitions/classement-individuel');
 await expect(admin.getByRole('cell',{name:'Alice Exemple',exact:true})).toBeVisible();
 await expect(admin.getByRole('columnheader',{name:'Open Club Double · Démonstration',exact:true})).toBeVisible();
 await screenshot(admin,'04-classement-public.png');
 await ds.goto('http://127.0.0.1:3008/admin/classement-individuel');
 await ds.waitForURL('**/unauthorized**');
 const blocked=await ds.request.post('http://127.0.0.1:3008/api/ranking-workflow/events/demo-double/actions',{headers:{Origin:'http://127.0.0.1:3008'},data:{action:'PUBLISH'}});
 expect(blocked.status()).toBe(403);
 const csrf=await admin.request.post('http://127.0.0.1:3008/api/ranking-workflow/events/demo-double/actions',{headers:{Origin:'https://evil.invalid'},data:{action:'PUBLISH'}});
 expect(csrf.status()).toBe(403);
 await ds.goto('http://127.0.0.1:3008/directeur-sportif');
 await ds.setViewportSize({width:390,height:844});
 await expect(ds.getByText('Open Club Double · Démonstration',{exact:true})).toBeVisible();
 await screenshot(ds,'05-mobile.png');
 expect(await ds.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await ds.getByRole('button',{name:'Open Club Double · Démonstration',exact:true}).click();
 await expect(ds.getByRole('heading',{name:'Open Club Double · Démonstration'})).toBeVisible();
 console.log('PASS: browser admin → correction DS → v3 → approval DS → final admin → publication; direct permissions, CSRF, public double points and mobile layout.');
}catch(e){console.error(e.message);console.error('Admin URL:',admin.url(),'DS URL:',ds.url());await screenshot(admin,'failure.png');process.exitCode=1;}finally{await browser.close()}
