import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8');
const db=new PGlite();
const owner='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
const phone=randomUUID(),pc=randomUUID(),blank={version:1,revision:0,current:null,completed:[]};
const cmd=async(kind,expected,device,action,record=null,id=randomUUID())=>(await db.query('select public.play_cloud_command($1,$2,$3,$4,$5,$6::jsonb) as result',[kind,expected,device,id,action,JSON.stringify(record)])).rows[0].result;
const as=async user=>{await db.exec('reset role; set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);};
try{
 await db.exec(read('tests/workflow/bootstrap.sql'));
 await db.exec(read('supabase/migrations/20260930110920_play_cloud_sync.sql'));
 await db.exec('set role anon');
 await assert.rejects(()=>db.query('select kind from public.play_cloud_sessions'),/permission denied/);
 await assert.rejects(()=>cmd('cricket',0,phone,'ENABLE',blank),/permission denied/);
 await as('');
 await assert.rejects(()=>cmd('cricket',0,phone,'ENABLE',blank),/UNAUTHENTICATED/);
 await as(owner);
 const id=randomUUID();
 let a=await cmd('cricket',0,phone,'ENABLE',blank,id);
 assert.equal(a.ok,true);assert.equal(a.row.revision,1);
 assert.deepEqual(await cmd('cricket',0,phone,'ENABLE',blank,id),a,'Lost response retries create once');
 await assert.rejects(()=>cmd('cricket',0,pc,'ENABLE',blank,id),/COMMAND_REUSED/);
 assert.equal((await cmd('cricket',0,pc,'ENABLE',blank)).ok,false,'Second device cannot replace a saved game');
 await assert.rejects(()=>db.query("update public.play_cloud_sessions set revision=42"),/permission denied/);
 await assert.rejects(()=>db.query("delete from public.play_cloud_sessions"),/permission denied/);
 await assert.rejects(()=>db.query("select last_signature from public.play_cloud_sessions"),/permission denied/);
 assert.equal((await cmd('cricket',1,pc,'SAVE',blank)).ok,false,'Only the writer saves');
 a=await cmd('cricket',1,phone,'SAVE',blank);
 assert.equal(a.row.revision,2);
 assert.equal((await cmd('cricket',1,pc,'CLAIM')).ok,false,'Stale takeover rejected');
 a=await cmd('cricket',2,pc,'CLAIM');
 assert.equal(a.row.writer_device,pc);assert.equal(a.row.revision,3);
 assert.equal((await cmd('cricket',2,phone,'SAVE',blank)).ok,false,'Old in-flight save cannot overwrite takeover');
 const replay=randomUUID();
 a=await cmd('cricket',3,pc,'SAVE',blank,replay);
 assert.equal(a.row.revision,4);
 assert.deepEqual(await cmd('cricket',3,pc,'SAVE',blank,replay),a,'Repeated save does not advance revision');
 await as(other);
 assert.equal((await db.query('select kind from public.play_cloud_sessions')).rows.length,0,'RLS hides another account');
 assert.equal((await cmd('cricket',4,pc,'CLAIM')).row,null,'Cannot claim another account');
 await cmd('cricket',0,pc,'ENABLE',blank);
 await as(owner);
 assert.equal((await db.query('select revision from public.play_cloud_sessions')).rows[0].revision,4,'Accounts remain separate');
 for(const kind of ['tictactoe','clock','bob27','connect4','conquest','bull500']) assert.equal((await cmd(kind,0,phone,'ENABLE',blank)).ok,true);
 assert.equal((await db.query('select kind from public.play_cloud_sessions')).rows.length,7);
 await assert.rejects(()=>cmd('unknown',0,phone,'ENABLE',blank),/INVALID_COMMAND/);
 await assert.rejects(()=>cmd('cricket',4,pc,'SAVE',{version:2,completed:[],current:null}),/INVALID_RECORD/);
 await assert.rejects(()=>cmd('cricket',4,pc,'SAVE',{...blank,padding:'x'.repeat(1000001)}),/INVALID_RECORD/);
 await db.exec('reset role');
 await db.query('delete from auth.users where id=$1',[owner]);
 assert.equal((await db.query('select count(*)::int as n from play_cloud_sessions')).rows[0].n,1,'Account removal cascades only its own sessions');
 console.log('PASS: cloud sync SQL — permissions, 7 kinds, account isolation, CAS, handover, idempotency, size bounds and account deletion');
} finally {await db.close();}
