"use client";
import { useState } from "react";
import { Clock3, RefreshCcw, Trophy, Undo2 } from "lucide-react";
import { ParticipantSetup } from "@/components/play/ParticipantSetup";
import { type PlayFormat } from "@/lib/play/format";
import { applyClockDart, createClockGame, endClockVisit, type ClockMode, type ClockMultiplier, type ClockState } from "@/lib/play/clock-engine";
type Props={currentDisplayName:string};const numbers=Array.from({length:20},(_,i)=>i+1);function copy(s:ClockState){return JSON.parse(JSON.stringify(s)) as ClockState;}
const MODES:Array<{id:ClockMode;title:string;desc:string}>=[{id:"SINGLE",title:"Simple",desc:"S1 → S20"},{id:"DOUBLE",title:"Double",desc:"D1 → D20"},{id:"TRIPLE",title:"Triple",desc:"T1 → T20"}];
export function ClockGame({currentDisplayName}:Props){const[mode,setMode]=useState<ClockMode>("SINGLE");const[format,setFormat]=useState<PlayFormat>("SOLO");const[names,setNames]=useState([currentDisplayName||"Joueur 1","Adversaire","Joueur 3","Joueur 4"]);const[game,setGame]=useState<ClockState|null>(null);const[history,setHistory]=useState<ClockState[]>([]);const updateName=(i:number,v:string)=>setNames(c=>c.map((n,x)=>x===i?v:n));function start(){setGame(createClockGame(mode,format,names));setHistory([]);}function dart(v:number,m:ClockMultiplier){if(!game||game.winnerSide!=null)return;setHistory(h=>[...h.slice(-49),copy(game)]);setGame(applyClockDart(game,v,m));}function pass(){if(!game||game.winnerSide!=null)return;setHistory(h=>[...h.slice(-49),copy(game)]);setGame(endClockVisit(game));}function undo(){const p=history.at(-1);if(!p)return;setGame(p);setHistory(h=>h.slice(0,-1));}
 if(!game)return <div className="practice-shell"><section className="practice-hero"><div><span>974DARTS PLAY · ENTRAÎNEMENT</span><h1>Tour de l’horloge</h1><p>Parcourez les numéros 1 à 20 dans l’ordre, avec le niveau de précision choisi.</p></div><Clock3/></section><ParticipantSetup format={format} onFormatChange={setFormat} names={names} onNameChange={updateName}/><section className="practice-mode-grid">{MODES.map(item=><button key={item.id} className={mode===item.id?"selected":""} onClick={()=>setMode(item.id)}><strong>{item.title}</strong><small>{item.desc}</small></button>)}</section><button className="practice-start" type="button" onClick={start}>Lancer le tour →</button></div>;
 const p=game.participants[game.activeParticipant];const side=game.sides[p.side];const required:ClockMultiplier=game.mode==="SINGLE"?1:game.mode==="DOUBLE"?2:3;return <div className="practice-shell"><section className="practice-matchbar"><div><span>TOUR DE L’HORLOGE · {game.mode}</span><strong>{p.name}</strong><small>{side.name} · cible {required===1?"S":required===2?"D":"T"}{side.target} · dart {game.dartsInVisit+1}/3</small></div><div><button onClick={undo} disabled={!history.length}><Undo2/>Annuler</button><button onClick={()=>setGame(null)}><RefreshCcw/>Quitter</button></div></section>{game.winnerSide!=null?<section className="practice-winner"><Trophy/><div><span>TOUR TERMINÉ</span><h2>{game.sides[game.winnerSide].name} gagne</h2><p>1 à 20 complétés en mode {game.mode.toLowerCase()}.</p></div><button onClick={start}>Rejouer</button></section>:null}<section className="practice-score-grid">{game.sides.map((s,i)=><article key={i} className={p.side===i?"active":""}><span>{s.finished?"TERMINÉ":"PROCHAINE CIBLE"}</span><h2>{s.name}</h2><strong>{s.finished?"✓":`${required===1?"S":required===2?"D":"T"}${s.target}`}</strong><small>{Math.max(0,s.target-1)}/20</small></article>)}</section>{game.winnerSide==null?<section className="practice-entry"><header><div><span>CIBLE ACTUELLE</span><strong>{required===1?"S":required===2?"D":"T"}{side.target}</strong></div><button onClick={pass}>Fin de volée →</button></header><div className="practice-numbers">{numbers.map(n=><button key={n} className={n===side.target?"target":""} onClick={()=>dart(n,required)}>{n}</button>)}</div><button className="practice-miss" onClick={()=>dart(0,required)}>MISS</button></section>:null}<section className="practice-history"><strong>Dernières flèches</strong>{game.log.length?game.log.map(e=><div key={e.id}><span>{game.participants[e.participant]?.name}</span><b>{e.dart}</b><small>{e.result}</small></div>):<p>Aucune flèche.</p>}</section></div>}
