"use client";
import { useState } from "react";
import { useLocalGame } from "@/components/play/useLocalGame";
import { LocalSessionBar } from "@/components/play/LocalSessionBar";
import { Clock3, Trophy, Undo2 } from "lucide-react";
import { TurnPanel } from "@/components/play/TurnPanel";
import { ParticipantSetup } from "@/components/play/ParticipantSetup";
import { type PlayFormat } from "@/lib/play/format";
import { applyClockDart, createClockGame, endClockVisit, type ClockMode, type ClockMultiplier, type ClockState } from "@/lib/play/clock-engine";
type Props={currentDisplayName:string;userId:string};const MODES:Array<{id:ClockMode;title:string;desc:string}>=[{id:"SINGLE",title:"Simple",desc:"S1 → S20"},{id:"DOUBLE",title:"Double",desc:"D1 → D20"},{id:"TRIPLE",title:"Triple",desc:"T1 → T20"}];
export function ClockGame({currentDisplayName,userId}:Props){const[mode,setMode]=useState<ClockMode>("SINGLE");const[format,setFormat]=useState<PlayFormat>("SOLO");const[names,setNames]=useState([currentDisplayName||"Joueur 1","Adversaire","Joueur 3","Joueur 4"]);const {game,history,start:saveStart,act,undo,controls}=useLocalGame<ClockState>("clock",userId);
 const updateName=(i:number,v:string)=>setNames(c=>c.map((n,x)=>x===i?v:n));
 function start(){saveStart(createClockGame(game?.mode??mode,game?.format??format,game?.participants.map(p=>p.name)??names));}
 function dart(v:number,m:ClockMultiplier){act(current=>applyClockDart(current,v,m));}
 function pass(){act(endClockVisit);}
 if(!controls.ready)return <LocalSessionBar controls={controls}/>;

 if(!game)return <div className="practice-shell"><LocalSessionBar controls={controls}/><section className="practice-hero"><div><span>974DARTS PLAY · ENTRAÎNEMENT</span><h1>Tour de l’horloge</h1><p>Parcourez les numéros 1 à 20 dans l’ordre, avec le niveau de précision choisi.</p></div><Clock3/></section><ParticipantSetup format={format} onFormatChange={setFormat} names={names} onNameChange={updateName}/><section className="practice-mode-grid">{MODES.map(item=><button key={item.id} className={mode===item.id?"selected":""} onClick={()=>setMode(item.id)}><strong>{item.title}</strong><small>{item.desc}</small></button>)}</section><button className="practice-start" type="button" onClick={start}>Lancer le tour →</button></div>;
 const p=game.participants[game.activeParticipant];const side=game.sides[p.side];const required:ClockMultiplier=game.mode==="SINGLE"?1:game.mode==="DOUBLE"?2:3;return <div className="practice-shell"><LocalSessionBar controls={controls}/><section className="practice-matchbar"><div><span>TOUR DE L’HORLOGE · {game.mode}</span><strong>{p.name}</strong><small>{side.name} · cible {required===1?"S":required===2?"D":"T"}{side.target} · {game.dartsInVisit}/3 fléchettes jouées</small></div><div><button onClick={undo} disabled={!history.length}><Undo2/>Annuler</button></div></section><TurnPanel blocked={controls.problem==="conflict"} player={p.name} nextPlayer={game.participants[(game.activeParticipant+1)%game.participants.length].name} darts={game.log.slice(0,game.dartsInVisit).reverse().map(e=>e.dart)} finished={game.winnerSide!=null} onDart={d=>dart(d.segment,(d.multiplier||1) as ClockMultiplier)} onNext={pass} onUndo={undo} canUndo={history.length>0} defaultMultiplier={required} hint={"Cible "+(required===1?"S":required===2?"D":"T")+side.target}/>{game.winnerSide!=null?<section className="practice-winner"><Trophy/><div><span>TOUR TERMINÉ</span><h2>{game.sides[game.winnerSide].name} gagne</h2><p>1 à 20 complétés en mode {game.mode.toLowerCase()}.</p></div><button onClick={start}>Rejouer</button></section>:null}<section className="practice-score-grid">{game.sides.map((s,i)=><article key={i} className={p.side===i?"active":""}><span>{s.finished?"TERMINÉ":"PROCHAINE CIBLE"}</span><h2>{s.name}</h2><strong>{s.finished?"✓":`${required===1?"S":required===2?"D":"T"}${s.target}`}</strong><small>{Math.max(0,s.target-1)}/20</small></article>)}</section><section className="practice-history"><strong>Dernières flèches</strong>{game.log.length?game.log.map(e=><div key={e.id}><span>{game.participants[e.participant]?.name}</span><b>{e.dart}</b><small>{e.result}</small></div>):<p>Aucune flèche.</p>}</section></div>}
