"use client";
import { useState } from "react";
import { useSyncedGame } from "@/components/play/useSyncedGame";
import { LocalSessionBar } from "@/components/play/LocalSessionBar";
import { CircleDot, Trophy, Undo2 } from "lucide-react";
import { TurnPanel } from "@/components/play/TurnPanel";
import { ParticipantSetup } from "@/components/play/ParticipantSetup";
import { type PlayFormat } from "@/lib/play/format";
import { applyBob27Dart, createBob27Game, endBob27Visit, type Bob27Multiplier, type Bob27State } from "@/lib/play/bob27-engine";
type Props={currentDisplayName:string;userId:string};export function Bob27Game({currentDisplayName,userId}:Props){const[format,setFormat]=useState<PlayFormat>("SOLO");const[names,setNames]=useState([currentDisplayName||"Joueur 1","Adversaire","Joueur 3","Joueur 4"]);const {game,history,start:saveStart,act,undo,controls}=useSyncedGame<Bob27State>("bob27",userId);
 const updateName=(i:number,v:string)=>setNames(c=>c.map((n,x)=>x===i?v:n));
 function start(){saveStart(createBob27Game(game?.format??format,game?.participants.map(p=>p.name)??names));}
 function dart(v:number,m:Bob27Multiplier){act(current=>applyBob27Dart(current,v,m));}
 function pass(){act(endBob27Visit);}
 if(!controls.ready)return <LocalSessionBar controls={controls}/>;

 if(!game && controls.sync?.active && controls.blocked)return <LocalSessionBar controls={controls}/>;
  if(!game)return <div className="practice-shell"><LocalSessionBar controls={controls}/><section className="practice-hero"><div><span>974DARTS PLAY · ENTRAÎNEMENT</span><h1>Bob’s 27</h1><p>Commencez à 27 points et travaillez D1 jusqu’à D20. Trois flèches par double.</p></div><CircleDot/></section><ParticipantSetup format={format} onFormatChange={setFormat} names={names} onNameChange={updateName} note="Disponible de 1 à 4 joueurs, chacun pour soi ou 2 vs 2."/><section className="practice-rules"><strong>Règle classique</strong><p>Chaque double touché ajoute sa valeur (D8 = +16). Si aucun des trois darts ne touche le double demandé, sa valeur est retirée. Le meilleur score après D20 gagne.</p></section><button className="practice-start" type="button" disabled={controls.blocked || controls.busy} onClick={start}>Commencer Bob’s 27 →</button></div>;
 const p=game.participants[game.activeParticipant];const side=game.sides[p.side];return <div className="practice-shell"><LocalSessionBar controls={controls}/><section className="practice-matchbar"><div><span>BOB’S 27</span><strong>{p.name}</strong><small>{side.name} · cible D{side.target} · {game.dartsInVisit}/3 fléchettes jouées</small></div><div><button onClick={undo} disabled={!history.length || controls.blocked || controls.busy}><Undo2/>Annuler</button></div></section><TurnPanel blocked={controls.problem==="conflict" || controls.blocked || controls.busy} player={p.name} nextPlayer={game.participants[(game.activeParticipant+1)%game.participants.length].name} darts={game.log.slice(0,game.dartsInVisit).reverse().map(e=>e.dart)} finished={game.finished} onDart={d=>dart(d.segment,(d.multiplier||1) as Bob27Multiplier)} onNext={pass} onUndo={undo} canUndo={history.length>0} defaultMultiplier={2} hint={game.dartsInVisit===3?"Volée comptabilisée · "+side.score+" points":"Cible D"+side.target}/>{game.finished?<section className="practice-winner"><Trophy/><div><span>PARCOURS TERMINÉ</span><h2>{game.winnerSides.map(i=>game.sides[i].name).join(" · ")}</h2><p>Meilleur score : {Math.max(...game.sides.map(s=>s.score))}</p></div><button disabled={controls.blocked || controls.busy} onClick={start}>Rejouer</button></section>:null}<section className="practice-score-grid">{game.sides.map((s,i)=><article key={i} className={p.side===i?"active":""}><span>{s.finished?"TERMINÉ":`CIBLE D${s.target}`}</span><h2>{s.name}</h2><strong>{s.score}</strong><small>points</small></article>)}</section><section className="practice-history"><strong>Dernières flèches</strong>{game.log.length?game.log.map(e=><div key={e.id}><span>{game.participants[e.participant]?.name}</span><b>{e.dart}</b><small>{e.result}</small></div>):<p>Aucune flèche.</p>}</section></div>}
