"use client";
import { useState } from "react";
import { CircleDot, RefreshCcw, Trophy, Undo2 } from "lucide-react";
import { ParticipantSetup } from "@/components/play/ParticipantSetup";
import { type PlayFormat } from "@/lib/play/format";
import { applyBob27Dart, createBob27Game, endBob27Visit, type Bob27Multiplier, type Bob27State } from "@/lib/play/bob27-engine";
type Props={currentDisplayName:string};const numbers=Array.from({length:20},(_,i)=>i+1);function copy(s:Bob27State){return JSON.parse(JSON.stringify(s)) as Bob27State;}
export function Bob27Game({currentDisplayName}:Props){const[format,setFormat]=useState<PlayFormat>("SOLO");const[names,setNames]=useState([currentDisplayName||"Joueur 1","Adversaire","Joueur 3","Joueur 4"]);const[game,setGame]=useState<Bob27State|null>(null);const[history,setHistory]=useState<Bob27State[]>([]);const[multiplier,setMultiplier]=useState<Bob27Multiplier>(2);const updateName=(i:number,v:string)=>setNames(c=>c.map((n,x)=>x===i?v:n));
 function start(){setGame(createBob27Game(format,names));setHistory([]);setMultiplier(2);}function dart(v:number,m:Bob27Multiplier=multiplier){if(!game||game.finished)return;setHistory(h=>[...h.slice(-49),copy(game)]);setGame(applyBob27Dart(game,v,m));}function pass(){if(!game||game.finished)return;setHistory(h=>[...h.slice(-49),copy(game)]);setGame(endBob27Visit(game));}function undo(){const p=history.at(-1);if(!p)return;setGame(p);setHistory(h=>h.slice(0,-1));}
 if(!game)return <div className="practice-shell"><section className="practice-hero"><div><span>974DARTS PLAY · ENTRAÎNEMENT</span><h1>Bob’s 27</h1><p>Commencez à 27 points et travaillez D1 jusqu’à D20. Trois flèches par double.</p></div><CircleDot/></section><ParticipantSetup format={format} onFormatChange={setFormat} names={names} onNameChange={updateName} note="Disponible de 1 à 4 joueurs, chacun pour soi ou 2 vs 2."/><section className="practice-rules"><strong>Règle classique</strong><p>Chaque double touché ajoute sa valeur (D8 = +16). Si aucun des trois darts ne touche le double demandé, sa valeur est retirée. Le meilleur score après D20 gagne.</p></section><button className="practice-start" type="button" onClick={start}>Commencer Bob’s 27 →</button></div>;
 const p=game.participants[game.activeParticipant];const side=game.sides[p.side];return <div className="practice-shell"><section className="practice-matchbar"><div><span>BOB’S 27</span><strong>{p.name}</strong><small>{side.name} · cible D{side.target} · dart {game.dartsInVisit+1}/3</small></div><div><button onClick={undo} disabled={!history.length}><Undo2/>Annuler</button><button onClick={()=>setGame(null)}><RefreshCcw/>Quitter</button></div></section>{game.finished?<section className="practice-winner"><Trophy/><div><span>PARCOURS TERMINÉ</span><h2>{game.winnerSides.map(i=>game.sides[i].name).join(" · ")}</h2><p>Meilleur score : {Math.max(...game.sides.map(s=>s.score))}</p></div><button onClick={start}>Rejouer</button></section>:null}<section className="practice-score-grid">{game.sides.map((s,i)=><article key={i} className={p.side===i?"active":""}><span>{s.finished?"TERMINÉ":`CIBLE D${s.target}`}</span><h2>{s.name}</h2><strong>{s.score}</strong><small>points</small></article>)}</section>{!game.finished?<section className="practice-entry"><header><div><span>CIBLE ACTUELLE</span><strong>D{side.target}</strong></div><button onClick={pass}>Fin de volée →</button></header><div className="practice-multipliers">{([1,2,3] as Bob27Multiplier[]).map(m=><button key={m} className={multiplier===m?"selected":""} onClick={()=>setMultiplier(m)}>{m===1?"SIMPLE":m===2?"DOUBLE":"TRIPLE"}</button>)}</div><div className="practice-numbers">{numbers.map(n=><button key={n} className={n===side.target?"target":""} onClick={()=>dart(n)}>{n}</button>)}</div><button className="practice-miss" onClick={()=>dart(0,1)}>MISS</button></section>:null}<section className="practice-history"><strong>Dernières flèches</strong>{game.log.length?game.log.map(e=><div key={e.id}><span>{game.participants[e.participant]?.name}</span><b>{e.dart}</b><small>{e.result}</small></div>):<p>Aucune flèche.</p>}</section></div>}
