import { buildParticipants, nextParticipantIndex, sideCount, sideName, type PlayFormat, type PlayParticipant } from "./format";
export type ClockMode="SINGLE"|"DOUBLE"|"TRIPLE";export type ClockMultiplier=1|2|3;
export type ClockSide={name:string;target:number;finished:boolean};export type ClockLogEntry={id:string;participant:number;dart:string;result:string};
export type ClockState={mode:ClockMode;format:PlayFormat;participants:PlayParticipant[];sides:ClockSide[];activeParticipant:number;dartsInVisit:number;winnerSide:number|null;log:ClockLogEntry[]};
export function createClockGame(mode:ClockMode,format:PlayFormat,names:string[]):ClockState{const participants=buildParticipants(format,names);return{mode,format,participants,sides:Array.from({length:sideCount(format)},(_,side)=>({name:sideName(format,side,participants),target:1,finished:false})),activeParticipant:0,dartsInVisit:0,winnerSide:null,log:[]};}
function cloneState(s:ClockState):ClockState{return{...s,participants:s.participants.map(p=>({...p})),sides:s.sides.map(x=>({...x})),log:s.log.map(e=>({...e}))};}
function requiredMultiplier(mode:ClockMode):ClockMultiplier{return mode==="SINGLE"?1:mode==="DOUBLE"?2:3;}
export function applyClockDart(current:ClockState,value:number,multiplier:ClockMultiplier){if(current.winnerSide!=null)return current;const state=cloneState(current);const pi=state.activeParticipant;const p=state.participants[pi];const side=state.sides[p.side];const required=requiredMultiplier(state.mode);const hit=value===side.target&&multiplier===required;const dart=value===0?"MISS":`${multiplier===1?"S":multiplier===2?"D":"T"}${value}`;let result=hit?`${dart} · cible ${side.target} validée`:`Il faut ${required===1?"S":required===2?"D":"T"}${side.target}`;
 if(hit){side.target+=1;if(side.target>20){side.target=20;side.finished=true;state.winnerSide=p.side;result+=" · tour terminé";}}
 state.log.unshift({id:`${Date.now()}-${Math.random()}`,participant:pi,dart,result});state.log=state.log.slice(0,24);state.dartsInVisit+=1;if(state.winnerSide==null&&state.dartsInVisit>=3){state.activeParticipant=nextParticipantIndex(pi,state.participants);state.dartsInVisit=0;}return state;}
export function endClockVisit(current:ClockState){if(current.winnerSide!=null)return current;const state=cloneState(current);state.activeParticipant=nextParticipantIndex(state.activeParticipant,state.participants);state.dartsInVisit=0;return state;}
